name: oneblock
version: '1.0-SNAPSHOT'
main: org.example.oneblock.OneBlockPlugin
api-version: '1.20'
commands:
  startoneblock:
    description: Starts a new OneBlock game
    usage: /<command>
    permission: oneblock.admin
  stoponeblock:
    description: Stops the current OneBlock game
    usage: /<command>
    permission: oneblock.admin
  gameinfo:
    description: Show information of the current stage
    usage: /<command>
  permission: oneblock.admin
  permissions:
    oneblock.admin:
      default: op

